Repository Mews-MIS/Mews-Client, pull requests merged in 2023-02, with the labels that each got.

#52 뉴스 페이지 - 메인 페이지 - 뉴스 상단 컴포넌트
  package-lock.json
  package.json
  src/components/NewsPostCard/index.tsx
  src/components/NewsPostCard/styles.ts
  src/components/NewsPostSlider/index.tsx
  src/components/NewsPostSlider/styles.ts
  src/pages/mypage/postlist/index.tsx
  src/pages/tmp/newsPostCards.ts
Labels: 💎 Feature, 🎨 스타일링

#54 뉴스 페이지 - 메인 페이지 - 뉴스 목록
  .vscode/launch.json
  package-lock.json
  package.json
  src/components/AuthorIntro/AuthorIntro.stories.tsx
  src/components/AuthorIntro/styles.ts
  src/components/NewListItem/NewsListItem.stories.tsx
  src/components/NewListItem/index.tsx
  src/components/NewListItem/styles.ts
  src/components/Pagination/index.tsx
  src/components/Pagination/pagination.module.css
  src/components/Pagination/styles.ts
  src/pages/newspage/index.tsx
  src/pages/newspage/styles.ts
  src/pages/newsview/styles.ts
  src/pages/tmp/newslist.ts
  src/pages/tmp/tmpImageURL.ts
  src/types/article.d.ts
Labels: 💎 Feature, 🎨 스타일링

#56 뉴스페이지 - 페이지 네이션 스타일링
  package-lock.json
  package.json
  src/components/Pagination/index.tsx
  src/components/Pagination/pagination.module.css
  src/components/Pagination/styles.ts
Labels: 🎨 스타일링

#57 뉴스 페이지 - 메인 페이지 - 뉴스 상단 컴포넌트 기능 추가
  src/components/NewsPostSlider/index.tsx
Labels: 💎 Feature, 🎨 스타일링

#59 뉴스페이지 - 메인페이지 제작
  src/components/NewsPostSlider/styles.ts
  src/components/Pagination/index.tsx
  src/pages/newspage/index.tsx
  src/pages/newspage/styles.ts
Labels: 🎨 스타일링

#53 뉴스페이지 - 학사일정 페이지 - 레이아웃 및 상태관리 로직
  package-lock.json
  package.json
  public/button/CollapseBtn.svg
  public/button/FoldBtn.svg
  public/button/NextMonthBtn.svg
  public/button/PreviousMonthBtn.svg
  src/components/CalendarDays/index.tsx
  src/components/CalendarDays/styles.ts
  src/components/CalendarLayout/CalendarLayout.stories.tsx
  src/components/CalendarLayout/index.tsx
  src/components/CalendarLayout/styles.ts
  src/components/DayItem/DayItem.stories.tsx
  src/components/DayItem/index.tsx
  src/components/DayItem/styles.ts
  src/components/MoveMonth/MoveMonth.stories.tsx
  src/components/MoveMonth/index.tsx
  src/components/MoveMonth/styles.ts
  src/components/PageTemplate/styles.ts
  src/components/ScheduleCategory/ScheduleCategory.stories.tsx
  src/components/ScheduleCategory/index.tsx
  src/components/ScheduleCategory/styles.ts
  src/components/ScheduleItem/ScheduleItem.stories.tsx
  src/components/ScheduleItem/index.tsx
  src/components/ScheduleItem/styles.ts
  src/components/ScheduleLayout/ScheduleList.stories.tsx
  src/components/ScheduleLayout/index.tsx
  src/components/ScheduleLayout/styles.ts
  src/pages/_app.tsx
  src/pages/calendar/index.tsx
  src/pages/calendar/styles.ts
  src/states/calendarInfoDetails.ts
  src/states/calendarInfoMonthYear.ts
  src/states/selectedDate.ts
Labels: 💎 Feature, 🎨 스타일링

#63 페이지 - 학사일정 캘린더 - api 통신 작업 완료
  src/components/CalendarLayout/index.tsx
  src/components/DayItem/index.tsx
  src/components/ScheduleCategory/index.tsx
  src/components/ScheduleLayout/index.tsx
  src/pages/calendar/index.tsx
  src/states/calendarInfoAll.ts
  src/states/calendarInfoDetails.ts
  src/states/calendarInfoMonthYear.ts
Labels: 💎 Feature

#66 검색페이지 - 최근 검색어 - 로컬 스토리지에 저장
  .gitignore
  package-lock.json
  package.json
  src/api/ArticleAPI.ts
  src/api/SearchAPI.ts
  src/components/ContentCard/index.tsx
  src/components/ContentRow/index.tsx
  src/components/ContentRow/styles.ts
  src/pages/index.tsx
  src/pages/search/_fragments/PopularKeyword/index.tsx
  src/pages/search/_fragments/RecentSearched/index.tsx
  src/pages/search/index.tsx
  src/pages/search/result/index.tsx
  src/services/HttpClient.ts
Labels: 💎 Feature

#67 검색페이지 - 검색 결과페이지 - api 연동
  src/api/SearchAPI.ts
  src/components/ContentRow/index.tsx
  src/components/NewListItem/index.tsx
  src/pages/index.tsx
  src/pages/search/result/_fragments/EditorProfile.tsx
  src/pages/search/result/_fragments/styles.ts
  src/pages/search/result/index.tsx
  src/pages/search/result/styles.ts
  src/types/article.d.ts
  src/types/editor.d.ts
Labels: 💎 Feature, 🎨 스타일링

#68 FEAT: API 연결 - 필진목록, 로그인 api 연결
  README.md
  src/api/ArticleAPI.ts
  src/api/CurationAPI.ts
  src/api/EditorAPI.ts
  src/api/UserAPI.ts
  src/components/AuthorIntro/index.tsx
  src/components/ContentRow/index.tsx
  src/components/MenuList/index.tsx
  src/pages/404.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/article/[id]/index.tsx
  src/pages/article/index.tsx
  src/pages/author/[id].tsx
  src/pages/author/styles.ts
  src/pages/authorInfo/index.tsx
  src/pages/calendar/index.tsx
  src/pages/index.tsx
  src/pages/introduce/author/index.tsx
  src/pages/login/index.tsx
  src/pages/login/styles.ts
Labels: 💎 Feature
