Repository Mews-MIS/Mews-Client, pull requests merged in 2023-01, with the labels that each got.

#2 core - 개발환경 세팅 - 개발환경 세팅
  .eslintrc.json
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .npmrc
  .prettierrc
  .storybook/main.js
  .storybook/preview.js
  README.md
  client/.eslintrc.json
  client/README.md
  client/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7
  client/node_modules/.cache/storybook/public/iframe.html
  client/node_modules/.cache/storybook/public/runtime_main.320d7296a8879c53d34c.hot-update.json
  client/node_modules/.cache/storybook/public/runtime~main.320d7296a8879c53d34c.hot-update.js
  client/node_modules/.cache/storybook/public/runtime~main.320d7296a8879c53d34c.hot-update.js.map
  client/node_modules/.cache/storybook/public/runtime~main.iframe.bundle.js
  client/node_modules/.cache/storybook/public/runtime~main.iframe.bundle.js.map
  client/package-lock.json
  client/package.json
  client/pages/_app.tsx
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/styles/Home.module.css
  client/styles/globals.css
  client/tsconfig.json
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/styles/Global.tsx
  src/styles/Theme.ts
  tsconfig.json
Labels: 📦 개발 환경 세팅

#10 core-공통컴포넌트-contentRow 작업
  src/components/ContentRow/ContentRow.stories.tsx
  src/components/ContentRow/index.tsx
  src/components/ContentRow/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#11 core-공통컴포넌트-필진 소개란 작업
  package-lock.json
  src/components/AuthorIntro/AuthorIntro.stories.tsx
  src/components/AuthorIntro/index.tsx
  src/components/AuthorIntro/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#13 core-공통컴포넌트-TopNavBar 작업
  package-lock.json
  package.json
  public/icon/CloseMenu.svg
  public/icon/Hamberger.svg
  public/icon/Logo.svg
  public/icon/SearchIcon.svg
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/TopNavBar/TopNavBar.stories.tsx
  src/components/TopNavBar/index.tsx
  src/components/TopNavBar/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#15 feat: 공통 컨테이너 제작 및 스토리 코드 추가
  .eslintrc.json
  src/components/AuthorIntro/index.tsx
  src/components/AuthorIntro/styles.ts
  src/components/ContentCard/index.tsx
  src/components/ContentWrapper/ContentWrapper.stories.tsx
  src/components/ContentWrapper/index.tsx
  src/components/ContentWrapper/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#18 Core - 공통 컴포넌트 - 프로필 사진 컨테이너
  next.config.js
  src/components/ContentWrapper/ContentWrapper.stories.tsx
  src/components/ProfileImageContainer/ProfileImageContainer.stories.tsx
  src/components/ProfileImageContainer/index.tsx
  src/components/ProfileImageContainer/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#23 메인페이지 - 레이아웃 - 구현
  src/components/CardSlider/styles.ts
  src/components/ContentCard/ContentCard.stories.tsx
  src/components/ContentCard/index.tsx
  src/components/ContentCard/styles.ts
  src/components/ContentRow/index.tsx
  src/components/ContentWrapper/styles.ts
  src/components/Menu/index.tsx
  src/pages/index.tsx
  src/pages/tmp/Curations.ts
  src/pages/tmp/mySubscribeArticle.ts
  src/pages/tmp/newArticle.ts
  src/pages/tmp/topView.ts
  src/types/article.d.ts
Labels: 💎 Feature, 🎨 스타일링

#26 Page - 검색페이지 - 레이아웃
  public/icon/ClockIcon.svg
  src/components/ContentWrapper/styles.ts
  src/pages/index.tsx
  src/pages/search/_fragments/PopularKeyword/index.tsx
  src/pages/search/_fragments/PopularKeyword/styles.ts
  src/pages/search/_fragments/RecentSearched/index.tsx
  src/pages/search/_fragments/RecentSearched/styles.ts
  src/pages/search/_fragments/RecommendKeyword/index.tsx
  src/pages/search/_fragments/RecommendKeyword/styles.ts
  src/pages/search/_fragments/SearchBar/index.tsx
  src/pages/search/_fragments/SearchBar/styles.ts
  src/pages/search/data.ts
  src/pages/search/index.tsx
  src/pages/search/result/index.tsx
  src/pages/search/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#29 fix: 디렉토리 대소문자 충돌 버전관리 버그 해결
  src/pages/MyPage/MyPage.stories.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/styles.ts
  src/pages/mypage/edit/index.tsx
  src/pages/mypage/edit/styles.ts
Labels: 👿 버그

#32 마이페이지 - 프로필 수정 페이지 - 프로필 이미지 업로드 및 미리보기
  src/components/EditProfileImage/index.tsx
  src/components/EditProfileImage/styles.ts
  src/pages/mypage/index.tsx
  src/pages/tmp/tmpImageURL.ts
Labels: 💎 Feature

#37 햄버거 버튼 - 페이지 및 연관 컴포넌트 - 라우팅
  src/components/AuthorIntro/index.tsx
  src/components/AuthorIntro/styles.ts
  src/components/BackBtn/BackBtn.stories.tsx
  src/components/BackBtn/index.tsx
  src/components/BackBtn/styles.ts
  src/components/Menu/Menu.stories.tsx
  src/components/Menu/index.tsx
  src/components/Menu/styles.ts
  src/components/MenuItem/index.tsx
  src/components/MenuItem/styles.ts
  src/components/MenuList/MenuList.stories.tsx
  src/components/MenuList/index.tsx
  src/components/MenuList/styles.ts
  src/components/TopNavBar/index.tsx
  src/pages/introduce/author/index.tsx
  src/pages/introduce/author/styles.ts
  src/pages/introduce/mews/index.tsx
  src/pages/introduce/mews/styles.ts
  src/pages/tmp/authors.ts
Labels: 💎 Feature, 🎨 스타일링

#39 뉴스페이지 - 작성자 정보 페이지
  src/components/ContentWrapper/styles.ts
  src/pages/authorInfo/index.tsx
  src/pages/authorInfo/styles.ts
  src/pages/tmp/infiniteArticle.ts
Labels: 💎 Feature, 🎨 스타일링

#41 코어 - 레이아웃 - 레이아웃 제작 및 적용
  src/components/CardSlider/styles.ts
  src/components/ContentCard/styles.ts
  src/components/ContentRow/styles.ts
  src/components/ContentWrapper/styles.ts
  src/components/Layout/index.tsx
  src/components/TopNavBar/styles.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/search/_fragments/SearchBar/styles.ts
  src/pages/search/index.tsx
  src/pages/search/styles.ts
Labels: 💎 Feature, 🎨 스타일링

#48 pages - 오류 처리페이지 작업
  src/pages/404.tsx
Labels: 💎 Feature, 🎨 스타일링

#49 페이지 - 페이지 스타일링
  src/components/ContentCard/styles.ts
  src/components/ContentRow/index.tsx
  src/components/ContentRow/styles.ts
  src/components/ContentWrapper/styles.ts
  src/components/PageTemplate/index.tsx
  src/components/PageTemplate/styles.ts
  src/components/TopNavBar/index.tsx
  src/components/TopNavBar/styles.ts
  src/pages/index.tsx
  src/pages/search/styles.ts
Labels: 🎨 스타일링
